# Generated by Django 4.1.2 on 2022-10-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(default='https://i.imgur.com/PdEQAt6.jpg'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
