# Generated by Django 4.1.2 on 2022-10-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_published',
            new_name='last_edited',
        ),
    ]
