# Generated by Django 4.1.2 on 2022-10-13 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_date_published_article_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_edited',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 1, 33, 2, 11416)),
        ),
    ]
