# Generated by Django 4.1.2 on 2022-10-13 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_summary_alter_article_last_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-last_edited']},
        ),
        migrations.AlterField(
            model_name='article',
            name='last_edited',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 21, 48, 48, 407095)),
        ),
    ]
