# Generated by Django 4.1.2 on 2022-10-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.URLField(default='https://i.imgur.com/a3vO917.jpg'),
        ),
    ]
